# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nansense',
                'doc_host': 'https://peterwinter.github.io',
                'git_url': 'https://github.com/peterwinter/nansense',
                'lib_path': 'nansense'},
  'syms': {'nansense.core': {'nansense.core.foo': ('core.html#foo', 'nansense/core.py')}}}
